version: "3.7"
services:

  traefik:
    image: ${TRAEFIK_IMG}
    restart: unless-stopped
    container_name: ${TRAEFIK_NAME}
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.toml:/etc/traefik/traefik.toml"
    networks:
      - backend

networks:
  backend:
    external:
      name: ${NETWORK}
