version: "2"
services:

  redis:
    image: ${REDIS_IMG}
    restart: unless-stopped
    container_name: ${REDIS_NAME}
    ports:
      - "6379"
    networks:
      - backend

networks:
  backend:
    external:
      name: ${NETWORK}
