version: "3.7"

services:
  apollo:
    image: ${APOLLO_IMG}
    restart: unless-stopped
    container_name: ${APOLLO_NAME}
    depends_on:
      - apollo-db
    ports:
      - "8080:8080"
      - "8070:8070"
    labels:
      - "traefik.http.routers.apollo.rule=Host(`${APOLLO_HOST}`)"
    environment:
      - VIRTUAL_HOST=${APOLLO_HOST}
      - VIRTUAL_PORT=8070
    links:
      - apollo-db
    networks:
      - backend

  apollo-db:
    image: mysql:5.7
    container_name: apollo-db
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "13306:3306"
    volumes:
      - ./apollo/sql:/docker-entrypoint-initdb.d
      - "apollo_dbdata:/var/lib/mysql"
    networks:
      - backend

networks:
  backend:
    external:
      name: ${NETWORK}

volumes:
  apollo_dbdata: