version: "2"
services:

  mariadb:
    image: ${MARIADB_IMG}
    restart: always
    container_name: ${MARIADB_NAME}
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - "mariadb_data:/var/lib/mysql"
    networks:
      - backend

networks:
  backend:
    external:
      name: ${NETWORK}

volumes:
  mariadb_data:
