version: "3.7"

services:
  adminer:
    image: ${ADMINER_IMG}
    restart: unless-stopped
    container_name: ${ADMINER_NAME}
    ports:
      - "8080"
    labels:
      - "traefik.http.routers.adminer.rule=Host(`${ADMINER_HOST}`)"
    environment:
      - VIRTUAL_HOST=${ADMINER_HOST}
      - VIRTUAL_PORT=8080
      - ADMINER_DESIGN=nette
    networks:
      - backend

networks:
  backend:
    external:
      name: ${NETWORK}
