version: "3.7"

services:
  phpmyadmin:
    image: ${PHPMYADMIN_IMG}
    restart: unless-stopped
    container_name: ${PHPMYADMIN_NAME}
    ports:
      - "80"
    labels:
      - "traefik.http.routers.phpmyadmin.rule=Host(`${PHPMYADMIN_HOST}`)"
    environment:
      - PMA_HOST=${MARIADB_NAME}
      - VIRTUAL_HOST=${PHPMYADMIN_HOST}
      - VIRTUAL_PORT=80
    networks:
      - backend

networks:
  backend:
    external:
      name: ${NETWORK}
