version: "2"
services:

  redis:
    image: ${REDIS_IMG}
    restart: unless-stopped
    container_name: ${REDIS_NAME}
    ports:
      - "6379"
    volumes:
      - "./redis.conf:/etc/redis.conf"
    networks:
      - backend
    command: redis-server /etc/redis.conf

networks:
  backend:
    external:
      name: ${NETWORK}
