version: "2"
services:

  jaeger:
    image: ${JAEGER_IMG}
    restart: unless-stopped
    container_name: ${JAEGER_NAME}
    ports:
      - "5775:5775/udp" # [agent] accept zipkin.thrift over compact thrift protocol (deprecated, used by legacy clients only)
      - "6831:6831/udp" # [agent] accept jaeger.thrift over compact thrift protocol
      - "6832:6832/udp" # [agent] accept jaeger.thrift over binary thrift protocol
      - "5778:5778" # [agent] serve configs
      - "16686:16686" # [query] jaeger ui
      - "14268:14268" # [collector] accept jaeger.thrift directly from clients
      - "14250:14250" # [collector] accept model.proto
      - "9411:9411" # [collector] Zipkin compatible endpoint (optional)
    environment:
      - VIRTUAL_HOST=${JAEGER_HOST}
      - VIRTUAL_PORT=16686
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    networks:
      - backend

networks:
  backend:
    external:
      name: ${NETWORK}
