version: "3.7"

services:
  xxl-job-admin:
    image: ${XXLJOB_IMG}
    restart: unless-stopped
    container_name: ${XXLJOB_NAME}
    depends_on:
      - xxl-job-admin-db
    links:
      - xxl-job-admin-db
    ports:
      - "8088:8080"
    labels:
      - "traefik.http.routers.xxljob.rule=Host(`${XXLJOB_HOST}`)"
    environment:
      PARAMS: "--spring.datasource.url=jdbc:mysql://xxl-job-admin-db:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8 --spring.datasource.username=root --spring.datasource.password=my-secret-pw"
    networks:
      - backend
  xxl-job-admin-db:
    image: ${MYSQL_IMG}
    container_name: xxl-job-admin-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "23306:3306"
    volumes:
      - ./xxl-job-admin:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --lower-case-table-names=1
    networks:
      - backend

networks:
  backend:
    external:
      name: ${NETWORK}
