version: "3.7"
services:

  mariadb:
    image: ${MARIADB_IMG}
    restart: unless-stopped
    container_name: ${MARIADB_NAME}
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - "mariadb_data:/var/lib/mysql"
      - "./mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf"
    networks:
      - backend

networks:
  backend:
    external:
      name: ${NETWORK}

volumes:
  mariadb_data:
