version: "3"
services:

  laravel:
    image: ${NGINX_PHP_IMG}
    restart: always
    container_name: ${LARAVEL_NAME}
    ports:
      - "80"
    environment:
      - VIRTUAL_HOST=${LARAVEL_HOST}
      - VIRTUAL_PORT=80
    volumes:
      - "${PWD}/laravel:/app"
      - "${PWD}/laravel.env:/app/.env"
      - "${PWD}/laravel.sh:/start.sh"
    networks:
      - backend

networks:
  backend:
    external:
      name: ${NETWORK}
