version: "3.7"

services:
  clickhouse:
    image: ${CLICKHOUSE_IMG}
    restart: unless-stopped
    container_name: ${CLICKHOUSE_NAME}
    ports:
      - "8123"
      - "9000"
      - "9009"
    volumes:
      - "clickhouse_data:/var/lib/clickhouse"
    networks:
      - backend
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

networks:
  backend:
    external:
      name: ${NETWORK}

volumes:
  clickhouse_data:
