# boot up baisc services
version: "3"
services:

  mariadb:
    image: ${MARIADB_IMG}
    restart: always
    container_name: ${MARIADB_NAME}
    ports:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - "mariadb_data:/var/lib/mysql"
    networks:
      - backend

  nginx-proxy:
    image: ${NGINX_PROXY_IMG}
    restart: always
    container_name: ${NGINX_PROXY_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    networks:
      - backend

  redis:
    image: ${REDIS_IMG}
    restart: always
    container_name: ${REDIS_NAME}
    ports:
      - "6379"
    networks:
      - backend

networks:
  backend:
    external:
      name: ${NETWORK}

volumes:
  mariadb_data:
