version: "3.7"

services:
  portainer:
    image: ${PORTAINER_IMG}
    restart: unless-stopped
    container_name: ${PORTAINER_NAME}
    ports:
      - "9000"
    labels:
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_HOST}`)"
    environment:
      - VIRTUAL_HOST=${PORTAINER_HOST}
      - VIRTUAL_PORT=9000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    networks:
      - backend

networks:
  backend:
    external:
      name: ${NETWORK}

volumes:
  portainer_data:
