@host=localhost
@port=9200

###

GET http://{{host}}:{{port}}/_cat/health

###
PUT http://{{host}}:{{port}}/twitter/_doc/1?pretty
Content-Type: application/json; charset=utf-8

{
    "user": "kimchy",
    "post_date": "2009-11-15T13:12:00",
    "message": "Trying out Elasticsearch, so far so good?"
}

###
PUT http://{{host}}:{{port}}/twitter/_doc/2?pretty
Content-Type: application/json; charset=utf-8

{
    "user": "kimchy",
    "post_date": "2009-11-15T14:12:12",
    "message": "Another tweet, will it be indexed?"
}

###

PUT http://{{host}}:{{port}}/twitter/_doc/3?pretty
Content-Type: application/json; charset=utf-8

{
    "user": "elastic",
    "post_date": "2010-01-15T01:46:38",
    "message": "Building the site, should be kewl"
}

###
GET http://{{host}}:{{port}}/twitter/_doc/1?pretty=true

###
GET http://{{host}}:{{port}}/twitter/_doc/2?pretty=true

###
GET http://{{host}}:{{port}}/twitter/_doc/3?pretty=true

###
GET http://{{host}}:{{port}}/twitter/_search?q=user:kimchy&pretty=true

###
GET http://{{host}}:{{port}}/twitter/_search?pretty=true
Content-Type: application/json; charset=utf-8

{
    "query" : {
        "match" : { "user": "kimchy" }
    }
}

###
GET http://{{host}}:{{port}}/twitter/_search?pretty=true
Content-Type: application/json; charset=utf-8

{
    "query" : {
        "match_all" : {}
    }
}

###
GET http://{{host}}:{{port}}/twitter/_search?pretty=true
Content-Type: application/json; charset=utf-8

{
    "query" : {
        "range" : {
            "post_date" : { "from" : "2009-11-15T13:00:00", "to" : "2009-11-15T14:00:00" }
        }
    }
}
